### ISSUE TITLE
Enable php7

### ISSUE THREAD

**Issue by cycomarcooo** [ezekg/graft#6]
Hi, thanks for this new VM. I tried to enable php7 by setting through chef.json in the Vagranfile but it's not enough. The php5.6 module must be disabled and php7.0 enabled. I did it inside cookbooks/graft/recipes/php.rb by adding the following lines before restarting apache:

```
apache_module 'php5.6' do
  enable false
end

apache_module 'php7.0' do
  identifier "php7_module"
  filename "libphp7.0.so"
end
```

I'm not sure if I did it right since I had to also change the corresponding file inside berks-cookbooks/graft/ to make it work. Is there some sort of cache I should clear after altering something inside cookbooks(graft/recipes ?

**Comment by ezekg** [comment]
Like I said in the readme, I haven't built an officially supported way to change versions for PHP, MySQL, etc. You'll likely need to install the ChefDK tools, so that you can run `berks vendor`, which will output all of the VM's dependencies into `berks-cookbooks`, which is then loaded by Chef. You can read more at the bottom of the readme.

Most of the dependencies are defined within the `Berksfile`, with the exception of the custom Graft cookbooks, which pretty much orchestrate everything together into the final VM. When you run `berks vendor`, everything gets vendored into `berks-cookbooks` so that the end user doesn't need to have ChedDK or Berkshire installed to run the provisioners.

As for having to disable PHP 5.6, I'm not sure. You may have to destroy the VM and provision from scratch. I haven't done too much testing with changing dependency versions on a VM that is already built. We've been focusing on releasing our app, so this will likely be done later down the road. Let me know what you figure out.
